#linting & sast scanning 
name: code-quality

on:
    workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt  
      - name: Run linters
        run: flake8 app.py
      - name: Run SAST  
        run: bandit -r app.py
        continue-on-error: true  # Continue even if vulnerabilities are found

    