name: Deploy App to EC2

on:
  workflow_run:
    workflows: ["DevSecOps Workflow - End to End Pipeline"]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-python-app:latest .


      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-python-app:latest


      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker stop python-app || true
            docker rm python-app || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/simple-python-app:latest

            docker run -d \
              -p 5000:5000 \
              --name python-app \
              ${{ secrets.DOCKER_USERNAME }}/simple-python-app:latest